export const issuingRegistrarData = [
  {
    id: 1,
    qbid: "MET-IND-24-6gH5vcQ7",
    qbIdType: "Individual",
    registrationDate: "17-May-2024",
    certicateNo: "3034473952",
    validityPeriod: "17-May-2027",
    qbStatus: "ACTIVE",
    issuingRegistrar: "METROPOLITAN SAMPLE ONLY",
    nameOfRelyingRegistrar: "PHILIPPINE SAMPLE ONLY",
    dateOfEvaluation: "17-May-2024",
    nameOfPersonnelConductedEval: "Juan Dela Cruz",
    designationOfPersonnel: "Compliance Officer",
  },
  {
    id: 2,
    qbid: "MET-IND-24-6gH5vcQ7",
    qbIdType: "Individual",
    registrationDate: "17-May-2024",
    certicateNo: "3034473952",
    validityPeriod: "17-May-2027",
    qbStatus: "ACTIVE",
    issuingRegistrar: "METROPOLITAN SAMPLE ONLY",
    nameOfRelyingRegistrar: "PHILIPPINE SAMPLE ONLY",
    dateOfEvaluation: "17-May-2024",
    nameOfPersonnelConductedEval: "Juan Dela Cruz",
    designationOfPersonnel: "Compliance Officer",
  },
  {
    id: 3,
    qbid: "MET-IND-24-6gH5vcQ7",
    qbIdType: "Individual",
    registrationDate: "17-May-2024",
    certicateNo: "3034473952",
    validityPeriod: "17-May-2027",
    qbStatus: "ACTIVE",
    issuingRegistrar: "METROPOLITAN SAMPLE ONLY",
    nameOfRelyingRegistrar: "PHILIPPINE SAMPLE ONLY",
    dateOfEvaluation: "17-May-2024",
    nameOfPersonnelConductedEval: "Juan Dela Cruz",
    designationOfPersonnel: "Compliance Officer",
  },
  {
    id: 4,
    qbid: "MET-IND-24-6gH5vcQ7",
    qbIdType: "Individual",
    registrationDate: "17-May-2024",
    certicateNo: "3034473952",
    validityPeriod: "17-May-2027",
    qbStatus: "ACTIVE",
    issuingRegistrar: "METROPOLITAN SAMPLE ONLY",
    nameOfRelyingRegistrar: "PHILIPPINE SAMPLE ONLY",
    dateOfEvaluation: "17-May-2024",
    nameOfPersonnelConductedEval: "Juan Dela Cruz",
    designationOfPersonnel: "Compliance Officer",
  },
  {
    id: 5,
    qbid: "MET-IND-24-6gH5vcQ7",
    qbIdType: "Individual",
    registrationDate: "17-May-2024",
    certicateNo: "3034473952",
    validityPeriod: "17-May-2027",
    qbStatus: "ACTIVE",
    issuingRegistrar: "METROPOLITAN SAMPLE ONLY",
    nameOfRelyingRegistrar: "PHILIPPINE SAMPLE ONLY",
    dateOfEvaluation: "17-May-2024",
    nameOfPersonnelConductedEval: "Juan Dela Cruz",
    designationOfPersonnel: "Compliance Officer",
  },
];
export const centralRegistryData = [
  {
    id: 1,
    qbid: "MET-IND-24-6gH5vcQ7",
    qbName: "Individual",
    qbType: "17-May-2024",
    registrationDate: "3034473952",
    corControlNumber: "17-May-2027",
    validityPeriod: "ACTIVE",
    qbStatus: "METROPOLITAN SAMPLE ONLY",
    issuingRegistrar: "PHILIPPINE SAMPLE ONLY",
    relyingRegistrar: "17-May-2024",
  },
  {
    id: 1,
    qbid: "MET-IND-24-6gH5vcQ7",
    qbName: "Individual",
    qbType: "17-May-2024",
    registrationDate: "3034473952",
    corControlNumber: "17-May-2027",
    validityPeriod: "ACTIVE",
    qbStatus: "METROPOLITAN SAMPLE ONLY",
    issuingRegistrar: "PHILIPPINE SAMPLE ONLY",
    relyingRegistrar: "17-May-2024",
  },
  {
    id: 1,
    qbid: "MET-IND-24-6gH5vcQ7",
    qbName: "Individual",
    qbType: "17-May-2024",
    registrationDate: "3034473952",
    corControlNumber: "17-May-2027",
    validityPeriod: "ACTIVE",
    qbStatus: "METROPOLITAN SAMPLE ONLY",
    issuingRegistrar: "PHILIPPINE SAMPLE ONLY",
    relyingRegistrar: "17-May-2024",
  },
  {
    id: 1,
    qbid: "MET-IND-24-6gH5vcQ7",
    qbName: "Individual",
    qbType: "17-May-2024",
    registrationDate: "3034473952",
    corControlNumber: "17-May-2027",
    validityPeriod: "ACTIVE",
    qbStatus: "METROPOLITAN SAMPLE ONLY",
    issuingRegistrar: "PHILIPPINE SAMPLE ONLY",
    relyingRegistrar: "17-May-2024",
  },
  {
    id: 1,
    qbid: "MET-IND-24-6gH5vcQ7",
    qbName: "Individual",
    qbType: "17-May-2024",
    registrationDate: "3034473952",
    corControlNumber: "17-May-2027",
    validityPeriod: "ACTIVE",
    qbStatus: "METROPOLITAN SAMPLE ONLY",
    issuingRegistrar: "PHILIPPINE SAMPLE ONLY",
    relyingRegistrar: "17-May-2024",
  },
];

export const relyingRegistrarData = [
  {
    id: 1,
    qbid: "MET-IND-24-6gH5vcQ7",
    issuingRegistrar: "roar",
    qbStatus: "Active",
    certificateNo: "3034473952",
    validityPeriod: "17-May-2024",
  },
  {
    id: 1,
    qbid: "MET-IND-24-6gH5vcQ7",
    issuingRegistrar: "roar",
    qbStatus: "Active",
    certificateNo: "3034473952",
    validityPeriod: "17-May-2024",
  },
  {
    id: 1,
    qbid: "MET-IND-24-6gH5vcQ7",
    issuingRegistrar: "roar",
    qbStatus: "Active",
    certificateNo: "3034473952",
    validityPeriod: "17-May-2024",
  },
  {
    id: 1,
    qbid: "MET-IND-24-6gH5vcQ7",
    issuingRegistrar: "roar",
    qbStatus: "Active",
    certificateNo: "3034473952",
    validityPeriod: "17-May-2024",
  },
];

export const usersData = [
  {
    id: 1,
    username: "admin",
    password: "admin",
    email: "ancmorante@sec.gov.ph",
    registrarId: "A-001",
    registrarName: "SEC ADMIN",
    role: "admin",
  },
  {
    id: 1,
    username: "admin",
    password: "admin",
    email: "ancmorante@sec.gov.ph",
    registrarId: "A-001",
    registrarName: "SEC ADMIN",
    role: "admin",
  },
  {
    id: 1,
    username: "admin",
    password: "admin",
    email: "ancmorante@sec.gov.ph",
    registrarId: "A-001",
    registrarName: "SEC ADMIN",
    role: "admin",
  },
  {
    id: 1,
    username: "admin",
    password: "admin",
    email: "ancmorante@sec.gov.ph",
    registrarId: "A-001",
    registrarName: "SEC ADMIN",
    role: "admin",
  },
  {
    id: 1,
    username: "admin",
    password: "admin",
    email: "ancmorante@sec.gov.ph",
    registrarId: "A-001",
    registrarName: "SEC ADMIN",
    role: "admin",
  },
];

export const submissionsData = [
  {
    id: 1,
    timestamp: "1/24/2026 6:34:38",
    submissionRefNo: "QBIRR-20260124-223436-DLVE",
    registrarName: "ABI SECURITIES",
    docType: "FORM39_QB",
    fileUrl: "https://www.google.com/url?q=https://drive.google.com",
  },
  {
    id: 1,
    timestamp: "1/24/2026 6:34:38",
    submissionRefNo: "QBIRR-20260124-223436-DLVE",
    registrarName: "ABI SECURITIES",
    docType: "FORM39_QB",
    fileUrl: "https://www.google.com/url?q=https://drive.google.com",
  },
  {
    id: 1,
    timestamp: "1/24/2026 6:34:38",
    submissionRefNo: "QBIRR-20260124-223436-DLVE",
    registrarName: "ABI SECURITIES",
    docType: "FORM39_QB",
    fileUrl: "https://www.google.com/url?q=https://drive.google.com",
  },
  {
    id: 1,
    timestamp: "1/24/2026 6:34:38",
    submissionRefNo: "QBIRR-20260124-223436-DLVE",
    registrarName: "ABI SECURITIES",
    docType: "FORM39_QB",
    fileUrl: "https://www.google.com/url?q=https://drive.google.com",
  },
  {
    id: 1,
    timestamp: "1/24/2026 6:34:38",
    submissionRefNo: "QBIRR-20260124-223436-DLVE",
    registrarName: "ABI SECURITIES",
    docType: "FORM39_QB",
    fileUrl: "https://www.google.com/url?q=https://drive.google.com",
  },
];
